version: '3'
services:
        mongodb:
                image: mongo
                container_name: mongodb-sadhu
                ports:
                        - 27017:27017
                volumes:
                        - ./data/db:/data/db
                restart: always
                # networks:
                #         - sadhu_nw
        web:
                build:
                        context: .
                image: sadhu-image
                container_name: sadhu-web
                volumes:
                        - .:/app
                ports:
                        - 8080:8080
                links:
                        - mongodb
                depends_on:
                        - mongodb
                # networks:
                # - sadhu_nw
                command: sadhu-web --host 0.0.0.0 --port 8080
# networks:
#         sadhu_nw:
#                 driver: bridge
        
